// <auto-generated />
namespace Manitouage1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class volunteer20210426 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(volunteer20210426));
        
        string IMigrationMetadata.Id
        {
            get { return "202104260447011_volunteer-2021-04-26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
