// <auto-generated />
namespace Manitouage1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _2021004062341_sandra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2021004062341_sandra));
        
        string IMigrationMetadata.Id
        {
            get { return "202104070341467_2021004062341_sandra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
