// <auto-generated />
namespace Manitouage1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testimonial_volunteers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testimonial_volunteers));
        
        string IMigrationMetadata.Id
        {
            get { return "202103182145267_testimonial_volunteers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
