// <auto-generated />
namespace Manitouage1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210804949amanda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210804949amanda));
        
        string IMigrationMetadata.Id
        {
            get { return "202104090149279_20210804949amanda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
