// <auto-generated />
namespace Manitouage1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _202104291829_sandra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202104291829_sandra));
        
        string IMigrationMetadata.Id
        {
            get { return "202104292229579_202104291829_sandra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
