// <auto-generated />
namespace Manitouage1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Manitouage_202103181634 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Manitouage_202103181634));
        
        string IMigrationMetadata.Id
        {
            get { return "202103182035007_Manitouage_202103181634"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
