// <auto-generated />
namespace Manitouage1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WafaM_20210422_1813 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WafaM_20210422_1813));
        
        string IMigrationMetadata.Id
        {
            get { return "202104222214000_WafaM_20210422_1813"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
