// <auto-generated />
namespace Manitouadge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _202105161119 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202105161119));
        
        string IMigrationMetadata.Id
        {
            get { return "202105161519385_202105161119"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
